---
title: "Hashing"
output: html_document
---
# Use Multiplex Demux

#Hashing

NEEDED FOR HASHING COMPARISON
png(filename = paste0(output.dir,"Plots/HTO/","08_umap_HTO_compare",".png"), width = 1500, height = 1000)
ggarrange(#DimPlot(seuratObj, reduction = "HTO_umap", group.by = "freemuxlet_guess", pt.size = 1)+ggtitle("Freemuxlet:label"),
  DimPlot(seuratObj, reduction = "HTO_umap", group.by = "hash.ID", pt.size = 1)+ggtitle("HTOdemux:label"),
  DimPlot(seuratObj, reduction = "HTO_umap", group.by = "MULTI_ID", pt.size = 1)+ggtitle("Multiseq:label"),
  #DimPlot(seuratObj, reduction = "HTO_umap", group.by = "freemuxlet_type", pt.size = 1)+ggtitle("Freemuxlet:type"),
  DimPlot(seuratObj, reduction = "HTO_umap", group.by = "HTO_classification.global", pt.size = 1)+ggtitle("HTOdemux:type"),
  ncol=3, nrow=2)
dev.off()
pdf(file =  paste0(output.dir,"Plots/HTO/","08_umap_HTO",".pdf"), width=10, height = 10)
# DimPlot(seuratObj, reduction = "HTO_umap", group.by = "freemuxlet_guess", pt.size = 1)+ggtitle("Freemuxlet:label")
DimPlot(seuratObj, reduction = "HTO_umap", group.by = "hash.ID", pt.size = 1)+ggtitle("HTOdemux:label")
DimPlot(seuratObj, reduction = "HTO_umap", group.by = "MULTI_ID", pt.size = 1)+ggtitle("Multiseq:label")
# DimPlot(seuratObj, reduction = "HTO_umap", group.by = "freemuxlet_type", pt.size = 1)+ggtitle("Freemuxlet:type")
DimPlot(seuratObj, reduction = "HTO_umap", group.by = "HTO_classification.global", pt.size = 1)+ggtitle("HTOdemux:type")
dev.off()



pdf(file = paste0(output.dir,"Plots/HTO/Overview_HTO.pdf"), width = 10, height = 10)
# FeaturePlot(seuratObj, features="Hashtag1", pt.size=0.10,label.size = 8,order=T)
# FeaturePlot(seuratObj, features="Hashtag2", pt.size=0.10,label.size = 8,order=T)
FeaturePlot(seuratObj, features=(TrueDetectedAbs),ncol=2, pt.size=0.1, label.size = 8,order=T)
DimPlot(seuratObj,group.by = "hash.ID", label = F, pt.size = 0.1) + ggtitle("HTOdemux")
DimPlot(seuratObj,split.by = "hash.ID", group.by = "hash.ID", label = F, pt.size = 0.1, ncol = 2) + ggtitle("HTOdemux")
DimPlot(seuratObj,group.by = "MULTI_ID", label = F, pt.size = 0.1) + ggtitle("MULTIseqDemux")
DimPlot(seuratObj,split.by = "MULTI_ID", group.by = "MULTI_ID", label = F, pt.size = 0.1, ncol = 2) + ggtitle("MULTIseqDemux")
DimPlot(seuratObj,group.by = "HTO_maxID", label = F, pt.size = 0.1) + ggtitle("MAX HTO count")
DimPlot(seuratObj,split.by = "HTO_maxID", group.by = "HTO_maxID", label = F, pt.size = 0.1, ncol = 2) + ggtitle("MAX HTO count")
dev.off()




### Fetch doublets from hashing ###
# -> uses Hashing data to find Doublets and Negatives

## Create HTO.data
# get hashtags present
tags <- rownames(seuratObj@assays$HTO@data)
# get barcodes
barcodes <- colnames(seuratObj@assays$HTO@data)
# make data frame 
HTO.data <- as_tibble(t(seuratObj@assays$HTO@data))
HTO.data$barcodes <- barcodes

## Add column with the highest hashtag and its value
max.tags <- c()
for (barcode in HTO.data$barcodes){
  #print(names(which.max(HTO.data[,barcode])))
  highest.HTO <- names(which.max(HTO.data[HTO.data$barcodes == barcode,]))
  #seuratObj@meta.data[rownames(seuratObj@meta.data) == barcode,"maxHTO"] <- highest.HTO
  max.tags <- append(max.tags, highest.HTO)
  #print(rownames(HTO.data[HTO.data[[barcode]] == max(HTO.data[[barcode]]),])) # for the maximum value
}
# merge with HTO.data
HTO.data <- cbind(HTO.data,max.tags)
# get value of the max hashtag
HTO.data$max.HTO.val <- apply(HTO.data[,tags],1,max)

#View(HTO.data)

## Visualize Hashtag Expression levels
p <- ggplot(HTO.data, aes(x=max.tags, y=max.HTO.val, fill=max.tags)) +
  geom_boxplot() +
  geom_jitter(color="black", size=0.4, alpha=0.9) +
  theme(
    legend.position="none",
    plot.title = element_text(size=18)
  ) +
  ggtitle("Check if expression levels are similar!") +
  xlab("") + theme_classic()
print(p)

## Create Hashtag.info table
hashtag.info <- as_tibble(tags)
colnames(hashtag.info) <- "tag"
# Add quantile percentages for each hashtag
q.data <- tibble()
for (tag in tags){
  # get quantile distribution (MANUAL threshold)
  q <- quantile(HTO.data[HTO.data$max.tags == tag,tag],probs = seq(0, 1, by=0.01), names = T)
  
  ##### AUTOMATIC expression cutoof detection #####
  # Add automated way to find dip between two peaks in data this will make the quantile cut_off less manual
  # based on assumtion: We will assume that a cell belongs to a # depending on what # it expresses the most
  # Why? It allows us to determine the lower expression limit of a # and at what point we can say a cell is positive for a #
  
  # find expression level were to place cutoff for each hashtag
  # In the plots we should see 2 peaks and cut_off needs to be in the middle of those peaks
  # We also need to make sure we actually see those peaks! if not this method probably will not work
  df <- HTO.data[,c(tag,"max.tags")]
  # get density with good precision
  #d <- density(df[[tag]])
  #In case you need a higher "precision"
  d <- density(df[[tag]], n=1e4)
  
  #Two ways to get highest Peak
  #d$x[d$y==max(d$y)]  #Gives you all highest Peaks
  #d$x[which.max(d$y)] #Gives you the first highest Peak
  #3 ways to get all Peaks
  d$x[c(F, diff(diff(d$y)>=0)<0)] #This detects also a plateau
  #d$x[c(F, diff(sign(diff(d$y)))<0)]
  #d$x[which(diff(sign(diff(d$y)))<0)+1]
  
  #In case you also want the height of the peaks
  peak_positions <- data.frame(d[c("x", "y")])[c(F, diff(diff(d$y)>=0)<0),]
  colnames(peak_positions) <- c(tag,"density")
  # extract peaks
  x_first_peak <- peak_positions[1,tag]
  x_second_peak <- peak_positions[2,tag]
  y_first_peak <- peak_positions[1,"density"]
  y_second_peak <- peak_positions[2,"density"]
  
  # Find minimum between peaks
  MinYDensity <- min(d$y[d$x > x_first_peak & d$x < x_second_peak])
  index <- which(d$y == MinYDensity)
  # min_expr <- d$x[index] #removed by clint!!
  min_expr<-q_manual_clint[tag]  #Clint
  
  ## Barplot
  #barplot <- ggplot(df, aes(x = .data[[tag]], fill = max.tags)) +
  #geom_histogram(position = "stack", bins = 75) +
  #theme_classic(base_size = 20) + ggtitle(paste0("Normalised ",tag, " Expression in all Cells"))
  ## Densityplot
  #densityplot <- ggplot(df, aes(x = .data[[tag]])) +
  #geom_density()+
  #geom_vline(linetype="dashed",xintercept = x_first_peak, color = "black") +
  #geom_vline(linetype="dashed",xintercept = x_second_peak, color = "black") +
  #geom_vline(linetype="dashed",xintercept = min_expr, color = "red") +
  #theme_classic() + ggtitle(paste0("Normalised ",tag, " Expression in all Cells"))
  #print(ggarrange(barplot,densityplot))
  
  pdf(file =  paste0(output.dir,"Plots/HTO/","10_Cutoff_plots_clint_v2_",tag,".pdf"), width=10, height = 10)
  print(
    ggplot(df, aes(x = .data[[tag]], fill = max.tags)) +
      geom_histogram(aes(y = ..density..),position = "stack", bins = 20) +
      geom_density(aes(x = .data[[tag]], fill = NULL)) +
      geom_vline(linetype="longdash",xintercept = x_first_peak, color = "black") +
      geom_vline(linetype="longdash",xintercept = x_second_peak, color = "black") +
      geom_vline(linetype="solid",xintercept = min_expr, color = "red", size = 2) +
      scale_x_continuous(breaks=seq(0, 10, 0.5)) + #Clint
      theme_classic(base_size = 20) +  
      ggtitle(paste0("Normalised ",tag, " Expression in all Cells")))
  dev.off()
  
  # Add automaticly found value to quantile range
  q["auto"] <- min_expr
  
  
  # Add information to tibble
  q.data <- rbind(q.data,as_tibble(as.list(q)))

}

## Added by Clint
## Sadly, too many peaks present in data for hashtag 7. Minimum between first two peaks is not a good cut-off!!
## Manually determined by the plots
q_manual_clint<-c(1.2,1.0,0.95,1.2) #1,2,3,4,5,6
names(q_manual_clint)<-tags

# merge with hashtag.info
hashtag.info <- cbind(hashtag.info,q.data)

#View(hashtag.info)  
## get for each cell in HTO.data expression of lower x% of all the cells for each hashtag! if cell in lower x% foor all tags -> negative
#q.cutoff <- "10%"
# loop over all values in HTO.data
for (c in 1:nrow(HTO.data)){
  for (tag in tags){
    # check if value is lower then x% quantile for all tags
    if (HTO.data[[tag]][c] <= hashtag.info[hashtag.info$tag == tag,q.cutoff]){
      HTO.data[c,paste0(tag,"_neg")] <- T
    } else {
      HTO.data[c,paste0(tag,"_neg")] <- F
    }
  }
}
# get colnames of negatives
negatives_cols <- c()
for (tag in tags){
  negatives_cols <- append(negatives_cols,paste0(tag,"_neg"))
}
# loop over all negative columns to get all negatives in lower left corner aka all cells who fall below the lower quantile for all hashtags
HTO.data$negative <- apply(HTO.data[,negatives_cols], 1, all)
table(HTO.data$negative)

# check if a hashtag is above the minimum quantile for multiple hashtags -> these are doublets!
for (c in 1:nrow(HTO.data)){
  # fetch status for all hashtags
  status <- c()
  for (tag in tags){
    if (HTO.data[c,tag] >= hashtag.info[hashtag.info$tag == tag,q.cutoff]){
      status <- append(status,T)
    } else {status <- append(status,F)}
  }
  # check if it is positive for multiple hashtags if True add true to doublet column
  if (sum(status==TRUE) > 1){
    HTO.data[c,"doublet"] <- T
  } else {HTO.data[c,"doublet"] <- F}
}
table(HTO.data$doublet)

## Merge DoubletFinder Information with HTO.data
# add barcode names to metadata
seuratObj@meta.data$barcodes <- rownames(seuratObj@meta.data)
# Fetch doublet information from DoubletFinder and the barcodes
data <- as_tibble(seuratObj@meta.data[,c("barcodes","DFPrediction")]) #Clint
# merge
HTO.data <- merge(HTO.data,data)

### ASSIGN TOOL RESULTS ###
# HTO cutoff method
HTO.data$HTO_Results <- NA
HTO.data[,"HTO_Results"] <- HTO.data$max.tags
HTO.data[HTO.data$negative == T,"HTO_Results"] <- "Negative"
HTO.data[HTO.data$doublet == T,"HTO_Results"] <- "Doublet"
table(HTO.data$HTO_Results)
#HTO.data$HTO_Results <- factor(HTO.data$HTO_Results)

# doubletFinder
HTO.data$DF_Results <- NA
HTO.data[HTO.data$DFPrediction == "Singlet","DF_Results"] <- "Singlet" #clint
HTO.data[HTO.data$DFPrediction == "Low Confidence" | HTO.data$DFPrediction == "Low Confidence adjusted","DF_Results"] <- "Doublet_low" #clint
HTO.data[HTO.data$DFPrediction == "High Confidence" | HTO.data$DFPrediction == "High Confidence adjusted","DF_Results"] <- "Doublet_high" #clint
table(HTO.data$DF_Results)


### ASSIGN DOUBLETS (HTO + DoubletFinder) HTO_STRICT_GUESS ###
# Hashtags first
HTO.data$HTO_STRICT_GUESS <- HTO.data$max.tags
# assign negatives
HTO.data[HTO.data$negative == T,"HTO_STRICT_GUESS"] <- "Negative"
# assign Doublets
HTO.data[HTO.data$doublet == T,"HTO_STRICT_GUESS"] <- "Doublet"
HTO.data[HTO.data$DF_Results == "Doublet_high","HTO_STRICT_GUESS"] <- "Doublet"
HTO.data[HTO.data$DF_Results == "Doublet_low","HTO_STRICT_GUESS"] <- "Doublet"
table(HTO.data$HTO_STRICT_GUESS)

### ASSIGN DOUBLETS (HTO + DoubletFinder) HTO_LENIENT_GUESS ###
# Hashtags first
HTO.data$HTO_LENIENT_GUESS <- HTO.data$max.tags
# assign negatives
HTO.data[HTO.data$negative == T,"HTO_LENIENT_GUESS"] <- "Negative"
# assign Doublets
HTO.data[HTO.data$doublet == T,"HTO_LENIENT_GUESS"] <- "Doublet"
HTO.data[HTO.data$DF_Results == "Doublet_high","HTO_LENIENT_GUESS"] <- "Doublet"
#HTO.data[HTO.data$doublet.class == "Doublet_low","HTO_LENIENT_GUESS"] <- "Doublet"
table(HTO.data$HTO_LENIENT_GUESS)

#HTO.data$DF_Results <- factor(HTO.data$DF_Results)
############################

## ADD TO SEURATOBJ
# fix stupid error
seuratObj@meta.data$HTOClass <- NULL # BUG FIX
seuratObj@meta.data$HTO_Results <- NULL 
seuratObj@meta.data$DF_Results <- NULL 
# seuratObj@meta.data$FM_Results <- NULL 
seuratObj@meta.data$HTO_STRICT_GUESS <- NULL 
seuratObj@meta.data$HTO_LENIENT_GUESS <- NULL 
# add to seurat metadata 
metadata <- seuratObj@meta.data
HTOClass <- HTO.data[,c("barcodes","HTO_Results","DF_Results","HTO_STRICT_GUESS","HTO_LENIENT_GUESS")]#"FM_Results",
metadata <- merge(metadata,HTOClass,by.x = "barcodes",by.y = "barcodes")

## Make correct order in metadata!!
rownames(metadata)<-metadata$barcodes
all(rownames(metadata)==rownames(seuratObj@meta.data))
metadata<-metadata[seuratObj@meta.data$barcodes,]
all(rownames(metadata)==rownames(seuratObj@meta.data))

seuratObj <- AddMetaData(seuratObj,metadata$HTO_Results,col.name = "HTO_Results")
seuratObj@meta.data$HTO_Results <- factor(seuratObj@meta.data$HTO_Results)

seuratObj <- AddMetaData(seuratObj,metadata$DF_Results,col.name = "DF_Results")
seuratObj@meta.data$DF_Results <- factor(seuratObj@meta.data$DF_Results)

# seuratObj <- AddMetaData(seuratObj,metadata$FM_Results,col.name = "FM_Results")
# seuratObj@meta.data$FM_Results <- factor(seuratObj@meta.data$FM_Results)

seuratObj <- AddMetaData(seuratObj,metadata$HTO_STRICT_GUESS,col.name = "HTO_STRICT_GUESS")
seuratObj@meta.data$HTO_STRICT_GUESS <- factor(seuratObj@meta.data$HTO_STRICT_GUESS)

seuratObj <- AddMetaData(seuratObj,metadata$HTO_LENIENT_GUESS,col.name = "HTO_LENIENT_GUESS")
seuratObj@meta.data$HTO_LENIENT_GUESS <- factor(seuratObj@meta.data$HTO_LENIENT_GUESS)

## Vis extra
LENIENT_GUESS<-seuratObj@meta.data$HTO_LENIENT_GUESS
LENIENT_GUESS_df <- as.data.frame(LENIENT_GUESS) %>%
  group_by(LENIENT_GUESS) %>%  dplyr::count() %>% dplyr::mutate(perc = round(100*n/ncells,2))
LENIENT_GUESS_results <- ggplot(LENIENT_GUESS_df, aes(x = LENIENT_GUESS, y = perc)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = paste("",perc,"%\nn=",n,"")), size=3.5, vjust = -0.3) +
  ggtitle("Classification according to pipeline Maarten") +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "", y = "Percentage of cells") +
  ylim(0, 125) +
  theme(axis.text.x = element_text(angle = 45, size=12, hjust = 1))

pdf(file = paste0(output.dir,"Plots/HTO/10_HTO_Lenient_guess_pipeline_Maarten_",experiment,".pdf"), width = 6, height = 5)
LENIENT_GUESS_results
dev.off()

seuratObj$MULTI_ID_merge<-paste0(seuratObj$orig.ident,"_",seuratObj$MULTI_ID)
seuratObj$LENIENT_GUESS_merge<-paste0(seuratObj$orig.ident,"_",seuratObj$HTO_LENIENT_GUESS)

pdf(file = paste0(output.dir,"Plots/HTO/Overview_",experiment,".pdf"), width = 10, height = 12)
DimPlot(seuratObj,group.by = "MULTI_ID_merge", label = F, pt.size = 0.1) + ggtitle("MULTIseqDemux")
DimPlot(seuratObj,split.by = "MULTI_ID_merge", group.by = "MULTI_ID_merge", label = F, pt.size = 0.1, ncol = 4) + ggtitle("MULTIseqDemux")
DimPlot(seuratObj,group.by = "LENIENT_GUESS_merge", label = F, pt.size = 0.1) + ggtitle("LENIENT_GUESS")
DimPlot(seuratObj,split.by = "LENIENT_GUESS_merge", group.by = "LENIENT_GUESS_merge", label = F, pt.size = 0.1, ncol = 4) + ggtitle("LENIENT_GUESS")
# DimPlot(seuratObj,group.by = "HTO_maxID", label = F, pt.size = 0.1) + ggtitle("MAX HTO count")
# DimPlot(seuratObj,split.by = "HTO_maxID", group.by = "HTO_maxID", label = F, pt.size = 0.1, ncol = 2) + ggtitle("MAX HTO count")
dev.off()

#######################################################################################################


## Hashing Testing and Notes
```{r}
#reading files 
#pbmc.umis <- readRDS("/brahms/shared/vignette-data/pbmc_umi_mtx.rds")




#Look for intersection between RNA and HTO 



## Subset RNA and HTO counts by joint cell barcodes
#pbmc.umis <- pbmc.umis[, joint.bcs]
#pbmc.htos <- as.matrix(pbmc.htos[, joint.bcs])





# VIB SCRIPT
# Put HTO in seprate assay
# seuratObj[['HTO']] <- CreateAssayObject(counts = rawData$`Custom`[,colnames(seuratObj)],min.cells=1)
# names(seuratObj)

### SPECIFY THE HASHTAG ANTIBODIES USED IN THE EXPERIMENT
#PresentHashingAntibodies<-c("Hashtag7","Hashtag8",
#                           "Hashtag9", "Hashtag10")

#
# HTOCounts<-as.matrix((rowSums(as.matrix((seuratObj@assays$HTO@counts)))))
# TrueDetectedAbs<-intersect(PresentHashingAntibodies, rownames(HTOCounts))

# after decting the trye HTOcounts
# Replaces the seuratobject HTO with only Truedectedabs

# After which follows normal preprocessing steps
```