---
title: "Pre-processing"
output: html_document
---

Pre-processing of CITE-seq data This Script is the first and will be used to pre-process SAM2 Provided data

```{r}

###############################################
#LOADING PACKAGE
###############################################

library("renv")
library("tidyverse")
library("Seurat")
library("SingleCellExperiment")
library("scater") 
library("scran") # Note for Windows --> Bluster dependencie doesnt compile properly in windows, mannulay add the bluster package to library. Download ---> https://bioc.r-universe.dev/bluster
library('fields')
#library('modes') #Niet in CRan
library("dplyr")
library("stringr")
library("readr")
library("ggplot2")


```

```{r}
#############################################
#RNA
############################################
setwd("/Users/samue/Desktop/Stage VIB/RawData/SAM2")
rawData <- Read10X("filtered_feature_bc_matrix")
rawDataRNA <- as.matrix(rawData$`Gene Expression`)
# Rawdata is 6.1 GB, it can be loaded but not examined ---> Took a subset of cells
rawDataRNA <- rawDataRNA[, 1:1000]

```


```{r}
sce<-SingleCellExperiment(list(counts=rawDataRNA))
# Everything starting with MT put in is.mito vector
is.mito <- grepl("^MT-", rownames(sce), ignore.case = TRUE)

#Scuttle function: addPerCellQC: Add QC metrics to a SummarizedExperiment
#QCmetric: Compute per-cell quality control metrics for a count matrix or a SingleCellExperiment. 

sce<- addPerCellQC(sce, subsets=list(Mito=is.mito))

# Make Metadata dataframe
metaData<-data.frame("staticNr"=colnames(rawDataRNA), 
                     "nGene"=sce$detected,
                     "nUMI"=sce$sum,
                     "percent.mito"=sce$subsets_Mito_percent, 
                     stringsAsFactors = F)
#Rownames fixen
rownames(metaData)<-metaData$staticNr
metaData$staticNr<-1 # Waarom kolom alles verander naar -1?


```


```{r}

# FILTERING Test

sampleName<-"GSM_2677817"
batch <- rep(sampleName, colnames(rawDataRNA) %>% length())

# Setting cut offs
# Nummber of genes
nmad_low_feature<-5
nmad_high_feature<-5

# Total counts all gene in a cell
nmad_low_UMI<-5
nmad_high_UMI<-5

# Precentage Mitchondrial gene
nmad_high_mito<-10

#Filter both Low and High outliers out
feature.drop.low <- isOutlier(sce$detected, nmads=nmad_low_feature, type="lower", log=TRUE,batch = batch)
feature.drop.high <- isOutlier(sce$detected, nmads=nmad_high_feature, type="higher", log=TRUE,batch = batch)
# Putting everything togheter
feature.drop<-as.logical(feature.drop.low + feature.drop.high,batch = batch)

#Filter both Low and High outliers out
libsize.drop.low <- isOutlier(sce$sum, nmads=nmad_low_UMI, type="lower", log=TRUE,batch = batch)
libsize.drop.high <- isOutlier(sce$sum, nmads=nmad_high_UMI, type="higher", log=TRUE,batch = batch)

# Putting everything togheter
libsize.drop<-as.logical(libsize.drop.low+libsize.drop.high)

#Filtering High out
mito.drop.high <- isOutlier(sce$subsets_Mito_percent, nmads=nmad_high_mito, type="higher",batch = batch)
mito.drop <- as.logical(mito.drop.high)


# Add dropped cells to metadata
metaData$nGene.drop=feature.drop
metaData$nUMI.drop=libsize.drop
metaData$mito.drop=mito.drop
metaData$final.drop=feature.drop | libsize.drop | mito.drop

#Remove the data out of sce
#sce <- sce[,!(libsize.drop | feature.drop | mito.drop)]

```

#Creating plot of the filter data
```{r}

#mad(sce$detected, nmads=5)

MitoPrecentage <- sce$subsets_Mito_percent

ggplot(metaData,aes(x=nUMI, y=nGene)) + 
  geom_point(aes(colour = MitoPrecentage ))+
  scale_colour_gradient(colours=terrain.colors(10))+
  
  
  
  geom_vline(xintercept = 1000,linetype="dotted", 
                color = "blue", size=1.5)+
   geom_vline(xintercept = 10000,linetype="dotted", 
                color = "red", size=1.5)+
geom_hline(yintercept = 1000,linetype="dotted", 
                color = "blue", size=1.5)+
   geom_hline(yintercept = 5000,linetype="dotted", 
                color = "red", size=1.5)


```
