---
title: "Post-precossing"
output: html_document
---
##Functions
```{r}
colorSomeCells<-function(clusterMatrix, coordsTable, cellsToColor){
  clusterMatrix$toColor=FALSE
  clusterMatrix[cellsToColor,which(colnames(clusterMatrix)=="toColor")]<-TRUE
  
  p1 <- ggplot()+
    geom_point(aes_string(x=colnames(coordsTable)[1],y=colnames(coordsTable)[2], colour=clusterMatrix$toColor), data=coordsTable, size=1) +
    scale_color_manual(values=c('TRUE'="orangered",'FALSE'="lightgray")) +
    theme_classic() +
    theme(plot.title = element_text(hjust = 0.5), legend.position = "right", legend.text=element_text(size=12))
  
  return(p1)
}

```



```{r}
## Packages
library("tidyverse")
library("Seurat")
library("SingleCellExperiment")
library("scater")
library("data.table")
library("ggpubr")
library("gridExtra")
library("fitdistrplus") 
library("dplyr")
library("plyr")
library("caret")
library("openxlsx")
library("ggplot2")
library("tibble")
library("scran")
library("limma")
library("ggrepel")
library("intrinsicDimension")
library("tidyr")
library("purrr")
library("ggrepel")
library("clustree")
library("limma")
library("patchwork")
library("future")
library('RColorBrewer')

```


#Post-Processing

After Basic filtering of data we want to take a closer look at each cluster that and see where further processing is necessary 


## Loading the Seurat Object
```{r}
setwd("/Users/samue/Desktop/Stage VIB/RawData/VBO004")
FileName <- basename(getwd())


#Loading Seaurat object
seuratObj <- readRDS(paste0("/Users/samue/Desktop/Stage VIB/Pre and Post processing Results/",FileName,"/Hashing/SeuratObj_HTO_",FileName,".rds"))



```


##Making Subsets of the data
```{r}

# Subset: Removing the Negative and Doublets
# Only HTO.data doublets removed ---> scdblfinder doublets are still in the the seuratObj 
ncol(seuratObj)
seuratObjR <- subset(seuratObj,seuratObj@meta.data$HTO_GUESS != "Doublet" & seuratObj@meta.data$HTO_GUESS != "Negative")
ncol(seuratObjR)

Idents(seuratObjR) <- "HTO_GUESS"

PlotSeurat <- DimPlot(seuratObj, label=T, repel=T )+ggtitle(paste0("Graph ",FileName))
PlotSeuratR <- DimPlot(seuratObjR, label=T, repel=T)+ggtitle(paste0("Graph",FileName))

PlotSeurat
PlotSeuratR 

Idents(seuratObjR) <- "seurat_clusters"

PlotSeuratRClust <- DimPlot(seuratObjR, label=T, repel=T )+ggtitle(paste0("Graph ",FileName," Clusters"))
PlotSeuratRClust

# ALL Doublets are removed

```

## Checking Unknow/ Suspicious cells
```{r}
# isolate Unknown cells
unknown_cells <- WhichCells(seuratObjR, expression = sctype_classification == "Unknown")
# Making a plot showcasing these genes


# Checking CDC1
PlotUnknown1 <- FeaturePlot(subset(seuratObjR, cells = unknown_cells),features = c("Cd81","Gcsam","Xcr1","Irf8"
))
PlotUnknown1 <- PlotUnknown1 +plot_annotation(title = "Controling if CDC1")


PlotUnknown1

```


# Loading VBO_merge Object
```{r}

nCellsR <-ncol(seuratObjR)

seuratObjVBO <- readRDS("/Users/samue/Desktop/Stage VIB/Pre and Post processing Results/VBO-Merge/seuratObj_paper_dietVBO_4-12_2024.rds")

#Subset to only VBO004
seuratObjVBO <- subset(seuratObjVBO,seuratObjVBO@meta.data$orig.ident==FileName)
PlotseuratVBO <- DimPlot(seuratObjVBO, label=T, repel=T )+ggtitle(paste0("Graph ",FileName," Clusters"))

# This is a WT conditions ---> Want to keep All cells 
# Using seuratVBO we select of our own seuratObjR the Late mature cells

# Comment Out
#seuratObjVBO <- subset(seuratObjVBO,seuratObjVBO@meta.data$Annotation_paper=="Late mature cDC1s")


#Fixing seuratVBO names to match our own seuratobject
VBOCellsSplit <- Cells(seuratObjVBO)
tmp <- str_split(VBOCellsSplit,"_")
VBOCells <-c()
for (i in 1:length(tmp)){
  VBOCells[i] <- tmp[[i]][1]
}

RenameCells(seuratObjVBO,new.names = VBOCells)


# Keep only the seuratObjR cells that are late mature cells according to the seuratObjVBO
seuratObjVBONAMES <- intersect(colnames(seuratObjR),VBOCells)
seuratObjR <- subset(seuratObjR, cells=seuratObjVBONAMES)

nCellsVBO <- ncol(seuratObjR)

PlotVBO <- data.frame(
  ObjectName= c("SeuratobjR Before" ,"seuratObjR After"),
  Cells = c(nCellsR,nCellsVBO)
)

# Added VBO_merge annotation

BarplotVBO <- ggbarplot(
  PlotVBO,
  x = "ObjectName",
  y = "Cells",
  label = TRUE,
  fill = "ObjectName",
  palette = c("steelblue", "tomato"),
)+
scale_y_continuous(
    breaks = seq(0, 14000, by = 2000)
  )+ggtitle("Before and After Filtering based on VBO_Merge ")


PlotseuratVBO

BarplotVBO


```




#Annontation Post-Processing of seuratObjR
```{r}
 PostAnnotClust <- DimPlot(seuratObj, reduction = "RNA_umap", label = TRUE, repel = TRUE, group.by = 'sctype_classification')+ggtitle(paste0("Graph: ",FileName," Annotation All cells Before"))

 PostAnnotClustR <- DimPlot(seuratObjR, reduction = "RNA_umap", label = TRUE, repel = TRUE, group.by = 'sctype_classification')+ggtitle(paste0("Graph: ",FileName," Annotation All cells After"))
 
 PostAnnotClust
 PostAnnotClustR

 # Adding VBO_Merge annotation to the seuratObjR
 # Already filter to the VBO datasets celltype (There is only 1 celltype so order of cells doesnt matter)
 seuratObjR$Annotation_VBO <- seuratObjVBO@meta.data$Annotation_paper
 
 
  PostAnnotClustVBO <- DimPlot(seuratObjR, reduction = "RNA_umap", label = TRUE, repel = TRUE, group.by = 'Annotation_VBO')+ggtitle(paste0("Graph: ",FileName," Annotation All cells based on VBOMerge"))
 
  PostAnnotClustVBO
  
```


 
# Notes
```{r}

blurb = paste("\n   Notes for The Post-Processing of VBO004\n",
         "
  - All doublets removed based on the HTO.data
  - Used VBO_Merge annontation to filter cells
  - Added the VBO_Merge annontation to seuratObjR
  ")
Notes <- ggplot() + 
  annotate("text", x = 4, y = 25, size=4, label = blurb) + 
  theme_void()
Notes

```

#Saving Object
```{r}
#Saving Object
setwd(paste0("/Users/samue/Desktop/Stage VIB/Pre and Post processing Results/",FileName,"/Post-process/"))

saveRDS(seuratObjR,paste0("SeuratObj_Post-Process_CDC1_",FileName,".rds"))

setwd(paste0("/Users/samue/Desktop/Stage VIB/Pre and Post processing Results/",FileName,"/Post-process/"))
pdf(paste0("Graphs Post-Process_",FileName,".pdf"), width = 14,
  height = 10)

PlotSeurat 
PlotSeuratR 
PostAnnotClust 
PostAnnotClustR
PlotUnknown1
if (exists("PlotUnknown")) {print(PlotUnknown)}
PostAnnotClustVBO
Notes
dev.off()


```


